### ISSUE TITLE
Tile drawing bug (*main_term->pict_hook)

### ISSUE THREAD

**Issue by s88100** [igroglaz/Tangaria#171]
Doesn't work correctly in SDL1 and Windows clients `(void)((*main_term->pict_hook)`
In V and PWMAngband code it works well.
for example, draw tiles on the entire screen
```
void do_test(void)
{
    term *main_term = angband_term[0];
    term *old = Term;

    int i, j;
    int w, h;

    uint16_t a;
    char c;
    uint16_t ta;
    char tc;

    // Activate the term
    Term_activate(main_term);

    // Get screen size
    w = (main_term->wid - COL_MAP - 1) / tile_width;
    h = (main_term->hgt - ROW_MAP - 1) / tile_height;

    // Screen
    for (i = 0; i < h; i++)
    {
        for (j = 0; j < w; j++)
        {
            Term_info(COL_MAP + j * tile_width, 
                ROW_MAP + i * tile_height, &a, &c, &ta, &tc);

            a = 0x81;
            c = '\xc9';

            // Display
            (void)((*main_term->pict_hook)(COL_MAP + j * tile_width, 
                ROW_MAP + i * tile_height, 1, &a, &c, &ta, &tc));
        }
    }

    // Actually flush the output
    Term_xtra(TERM_XTRA_FRESH, 0);

    // Restore the term
    Term_activate(old);
}
```
_PWMAngband_
![screenshot-1](https://github.com/igroglaz/Tangaria/assets/71586060/ae6fa428-9490-4714-8e28-19f2966d291b)

_Tangaria_
![screenshot-2](https://github.com/igroglaz/Tangaria/assets/71586060/c4cad7c1-ade3-46f7-822e-ad278228c9fb)

**Comment by s88100** [comment]
https://github.com/igroglaz/Tangaria/blob/456bb82b913ef042a8053078eca49506ca94201e/src/client/main-sdl.c#L5953
https://github.com/igroglaz/Tangaria/blob/456bb82b913ef042a8053078eca49506ca94201e/src/client/grafmode.c#L91
https://github.com/igroglaz/Tangaria/blob/456bb82b913ef042a8053078eca49506ca94201e/lib/tiles/list.txt#L38

**Comment by s88100** [comment]
checked 32x32.png 4096x4096
4096/32=128 (0...127)
0x7F = 127
https://github.com/igroglaz/Tangaria/blob/456bb82b913ef042a8053078eca49506ca94201e/src/client/main-sdl.c#L5950

In V and PWMAngband
https://github.com/angband/angband/blob/master/lib/tiles/list.txt#L34
https://github.com/draconisPW/PWMAngband/blob/eaa9e32a6450e0ca65f8efd57db0ccce0067763b/lib/tiles/list.txt#L38
with options code `do_test()` worked
`extra:1:0:0`
or `extra:0:0:0`

**Comment by s88100** [comment]
/tiles/list.txt _"end row" must be greater than 0, if double high tiles are used, and refer to the bottom half of the double row._
maybe it's like in V https://github.com/angband/angband/tree/master/lib/tiles/shockbolt
monsters use two tiles

**Comment by igroglaz** [comment]
we do not have two tiles monsters cause they are bad for multiplayer experience

**Comment by s88100** [comment]
fixed https://github.com/igroglaz/Tangaria/pull/172
```
'/tiles/list.txt'
extra:1:0:0
extra:mode->alphablend, mode->overdrawRow, mode->overdrawMax 
```
