### ISSUE TITLE
Ancient dragons drop 20 coins

### ISSUE THREAD

**Issue by draconisPW** [igroglaz/Tangaria#18]
It's more profitable to kill some drunks in town than killing an ancient dragon at 2500ft. I checked PWMAng code for some bug but didn't find any. The problem simply comes from level_golds.txt which defines absurd values for depths around dungeon level 45.

**Comment by igroglaz** [comment]
it shouldn't be 20g from D at 2500 as Tangaria does not have values less then 10 in level_golds.txt . Server got exact values from this repo... https://github.com/igroglaz/Tangaria/blob/master/lib/gamedata/level_golds.txt

2500 got `rate:50:15`
so it's 1.5x of normal ('selling' ON) drop there

so might be a bug.. or just weird RNG

**Comment by igroglaz** [comment]
which time did you meet this? I could check logs

**Comment by draconisPW** [comment]
I checked the code again. At that depth, the average drop is 60 gold with a spread value of 40, so it will generate 20-100 gold. Dropping 20 was on the very bottom of the scale. What I don't get is why you put a drop rate of 10 at 2250ft which is the same as in town. Doesn't feel right at all to get same amount of money from a drunk in town.

**Comment by igroglaz** [comment]
there is too much gold in mid-game, thats why I'm working on rebalancing it in gold drop table. It's experemental value and it will be changed in time.

For now I've just tested it with admin char - getting to 50 lvl depth I see ~200g per one gold pile (definitely not 20g) scattered around lvl. Sometimes you could meet much more gold in pile (like I've met one day). 

Anyway please, you are welcome to suggest adjustments to the table.

**Comment by draconisPW** [comment]
Strangely i've never experienced small piles of gold, just from mob drops. But I've tested it and there should be no difference at all, so it was just RNG. However there is clearly not too much gold in the mid game, as diving to 45-50 depth is level 40+ and not the mid game anymore. IMO the table is a bit off, the drop in gold should occur way earlier, maybe around 30-35. And not be that drastic (maybe stop at 20 instead of 10).

**Comment by draconisPW** [comment]
As I was saying, the midgame should be pretty much set around 30-35, which should be the lowest point for gold drop. I'm currently diving my level 43 character at depth 45 trying to get enough money to buy a book in market, but at this rate it will take me forever to have a chance. For me the table should stop going down at 30 then hit bottom for a while till probably 35 then up again.

**Comment by igroglaz** [comment]
my vision on stages:
early game: 0-30 (pre-ESP era)
mid-game: 30-45
end-game: 45+

I'm not sure about books 'accessibility' as I almost didn't play mages. As mages do not need certain consumables (where non-magic chars put their gold mostly), they should empty their pockets on books. But maybe book prices should be revamped in T cause of gold drop?

**Comment by draconisPW** [comment]
Well the problem is that there are not enough people playing. Take for example my sorceror: at my level, I've stored like 40 potions of healing that I don't use and I could put them on sale to get the gold I need. Or nice artifacts. But since there is nobody buying I have to rely on gold drops like I would in single player Angband. And in the endgame, mages will need a lot of potions of restore mana, which are expensive. Same as a melee character with potions of healing.

**Comment by igroglaz** [comment]
soon (tm) we will have more players and then it will be easier :) some folk could find book which you need and put it on sale too. for now the best scenario is just to try to find this book by yourself. or we could reduce it's price

**Comment by igroglaz** [comment]
https://github.com/igroglaz/Tangaria/commit/fddbad1ef14034c6f91685eca69c869b153af6f2
