### ISSUE TITLE
install script linux shortcomings…

### ISSUE THREAD

**Issue by Tokariew** [igroglaz/Tangaria#19]
https://raw.githubusercontent.com/igroglaz/Tangaria/master/tangaria-setup.sh

instead of using $HOME in script in most cases should be used:
$XDG_CONFIG_HOME for .pwmangrc
$XDG_DATA_HOME for save/score files and others…

specification of xdg base directory structure: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

.desktop files are usually in one of folder inside $XDG_DATA_DIRS usually ~/.local/share/applications/ so in $XDG_DATA_HOME/applications https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html https://wiki.archlinux.org/index.php/desktop_entries
and don't require to be executable so this line is not necessary:

```
chmod +x $INSTALL_DIR/pwmangclient.desktop
```

CPU_CORES have value of 1, and don't care about number of cores/threads…

one simplistic way to get number of threads:
```
CPU_CORES=$(cat /proc/cpuinfo | grep processor | wc -l)
```

pwangband will compile faster with it…

yum is dead… Fedora/RHEL/CentOS use dnf, and pretty sure that Suse don't have yum/dnf by default only zypper…

installing all of Development tools is extensive on rpm systems…

**Comment by s88100** [comment]
The main thing is to be universal for most distributions
CPU_CORES=$(cat /proc/cpuinfo | grep processor | wc -l) universal solution ?
at the top options INSTALL_DIR= change default path, CPU_CORES= to 8
for Fedora/RHEL/CentOS sudo dnf group install "Development Tools"
sudo dnf install SDL-devel SDL_ttf-devel SDL_mixer-devel SDL_image-devel ncurses-devel ?

**Comment by Tokariew** [comment]
for fedora/RHEL…
```
sudo dnf install {ncurses,SDL{,_{ttf,mixer,image}}}-devel wget make unzip automake gcc findutils
```
this instruction is for minimal installion of Fedora, should install all which is needed.

CPU_CORES=$(cat /proc/cpuinfo | grep processor | wc -l)  tested on fedora/manjaro/alpine/rasbian not sure about guix or other distros which not use standard file system layout

even with INSTALL_DIR there are still created hidden files in $HOME, which shouldn't be there…

**Comment by s88100** [comment]
I'll try to add a package builder (deb,rpm) Tangaria  auto-collector Makefiles for example a lot of mp3 files , and modify the code ./configure --prefix for custom version, and .desktop files in ~/.local/share/applications/ will interfere with the launch of packages, you can add in folder ~/Desktop or ~/.local/share/applications/
for example in wine removed the program win, .desktop file remained in the menu.

**Comment by Tokariew** [comment]
Sorry, I have weird assumption…
1. .desktop files if not in .local/share/application or in /usr/share/application will not show up in menu launcher… And will act like shortcut with icon, which is not very useful on console file manager like ranger/lf on minimalist linux installations. If You don't want to leave entries in menu launcher, maybe some uninstall script should be created too?  
2. creating deb/rpm for me seem like wasting time if appimage exist which is more universal.
3. hidden files in home folder are somewhat not welcome nowadays. There are guides how to move hidden files to location supporting xdg base directory specifications https://wiki.archlinux.org/index.php/XDG_Base_Directory#Partial

**Comment by s88100** [comment]
thanks for the information, the code needs to be corrected, linux way. Yes appimage is a good variant.

**Comment by igroglaz** [comment]
```
[19:16] Serega88: I think that you can close. Solved with CPU_CORES, .desktop files. If I decide with $XDG_CONFIG_HOME then add custom to Options. AppImage good variant, I'll add it to Options: create makefiles, create AppImage
[19:22] Serega88: But all packages (deb,rpm,AppImage) Angband, Mangband, TomeNet are set up by default (hidden files in home folder) I don't know about this. https://wiki.archlinux.org/index.php/XDG_Base_Directory#Partial
```
