### ISSUE TITLE
Misuse of effect:RANDOM

### ISSUE THREAD

**Issue by draconisPW** [igroglaz/Tangaria#23]
Looking at https://github.com/draconisPW/PWMAngband/issues/296, I found out that Tangaria is not using effect:RANDOM properly in many cases, resulting in wrong descriptions and incorrect effects. There are two rules to respect for this:
- RANDOM must be unique, there cannot be multiple RANDOM lines for the same object/activation, this will not work and there is no way to make this work -- you will need to remove the extra lines or group them in the same RANDOM
- RANDOM must be the last effect in the linked list, which means since the effects are parsed backwards that it must be the first effect defined in the object file

For example, Flask of Whisky should be changed to something like this:

effect:DRAIN_STAT:INT
dice:1
effect:DRAIN_STAT:WIS
dice:1
effect:TIMED_INC_NO_RES:PARALYZED
dice:11+1d8
effect:TIMED_INC:BLIND
dice:11+1d8
effect:TIMED_INC:IMAGE
dice:11+1d5
effect:TIMED_INC:AMNESIA
dice:11+1d8
effect:TIMED_INC:POISONED
dice:8+1d8
effect:TIMED_INC:SLOW
dice:11+1d11
effect:RANDOM
dice:8
effect:NOURISH:INC_BY
dice:1
effect:TIMED_INC:CONFUSED
dice:8+1d8
effect:TIMED_INC:BOLD
dice:50+1d20
effect:RESTORE_STAT:STR
effect:RESTORE_STAT:CON

Other erroneous objects:
- Pint~ of Fine Wine
- Cure Light Wounds
- Cure Serious Wounds
- Cure Critical Wounds
- Heroism
- Infravision
- Lose Memories
- Dragon Breath
- Pint~ of Fine Ale
- Ancient Vessel
- Magic Lamp

**Comment by igroglaz** [comment]
Thanks, fixed https://github.com/igroglaz/Tangaria/commit/fa02da1e06e11ee89d57f283091839f8c1a38cec ⚔️ 

It will be fun though to have possibility to assign multiple RANDOM to one item one day... 🐻
