### ISSUE TITLE
archlinux support

### ISSUE THREAD

**Issue by igroglaz** [igroglaz/Tangaria#29]
Folks in comments on the website ( https://tangaria.com/news/pwmangband-1-4-0-beta-16/ ) wrote about problems with Archlinux: 

_Every time I create a character, the game crashes with “Unknown packet type”_

_I have the same issue in Arch Linux. Did you resolve this? Mangclient works fine. Any help is appreciated._

I see their problem in log files.. @s88100 please could you help

**Comment by s88100** [comment]
Checked in virtualbox Manjaro (is based on Arch Linux), works fine.
`sudo pacman -S autoconf automake gcc glibc make sdl sdl_image sdl_mixer sdl_ttf unzip`
sorry i'm not an Arch Linux user, but if the problem is not solved then I will try to install Arch.

**Comment by igroglaz** [comment]
hm.. wait.. I suppose people are trying to connect the game with next version of PWMA... while Tangaria works at previous version for now. So it seems this is the issue.
