### ISSUE TITLE
hhmmssddmmyyyy as dump name

### ISSUE THREAD

**Issue by igroglaz** [igroglaz/Tangaria#4]
1) 
src\server\player-ui.c :
 file_putf(fff, "Time 2: %ld\n\n", p->death_info.time);

this is unix timestamp (time from 1970).. we need to output this time as:
hhmmssddmmyyyy
where:
hh = hour (24 format)
mm = minute
ss = second
dd = day 
mm = month
yyyy = year

eg:
21:48:56 17.07.2021

2) make character dump name with this format:

`<character_name>_<hhmmssddmmyyyy>.txt`

eg atm is 21:48:56 17.07.2021.. so filename:
Foo-21485617072021.txt

**Comment by igroglaz** [comment]
there is also  `file_putf(fff, "Time: %s\n\n", p->death_info.ctime);` which outputs such string:
Time: Sat Jul 17 21:56:38 2021

**Comment by s88100** [comment]
**\n** is known as new line character. While using this in printf ("\n"); it gives a line break. The output marker goes to next line.
Eg. `printf ("hello \nworld");`
Output - hello
world

**Comment by s88100** [comment]
keywords 'sizeof(dumpname)'
/src/server/netserver.c L6373, L6776
/src/server/display-ui.c L1819, L1830
https://github.com/igroglaz/Tangaria/blob/dev/src/server/display-ui.c#L1819
`strnfmt(dumpname, sizeof(dumpname), "%s-%s_%ld.txt", p->name, ht_show(&turn), p->death_info.time);`
name, turn, _date time
  Man3767-291449_140727027064626.txt

**Comment by igroglaz** [comment]
1) erm.. of course I know about \n ;) not sure why you mentioned it. new lines needed in dump file
2) yep, the task is to make proper data format. as current format is unix timestamp or ctime string

**Comment by igroglaz** [comment]
so.. the problem is:
death_info.time will output unix timestamp seconds - "The unix time stamp is a way to track time as a running **total of seconds**. This count starts at the Unix Epoch on January 1st, 1970 at UTC." ( https://www.unixtimestamp.com/ )

death_info.ctime output date in this format:
 Sat Jul 17 21:56:38 2021

But... we need this format:
hhmmssddmmyyyy

so the task is to take unix timestamp and calculate out of it needed format

**Comment by igroglaz** [comment]
there are plenty of examples in google how to format time from unix timestamp to our format.. we just need to choose one and implement it properly

**Comment by s88100** [comment]
The strftime() function formats date and time.
https://zetcode.com/articles/cdatetime/
https://stackoverflow.com/questions/3673226/how-to-print-time-in-format-2009-08-10-181754-811

sample src\server\player-ui.c
```
    /* Dump account (server dumps) */
    if (!p->dump_gen)
    {
        time_t timer;
        char buf[MSG_LEN];
        struct tm* tm_info;

        timer = time(NULL);
        tm_info = localtime(&timer);

        strftime(buf, MSG_LEN, "%H.%M.%S.%d.%m.%y", tm_info);

        file_put(fff, "\n  [Player information]\n\n");
        file_putf(fff, "Time: %s\n\n", buf);
    }
```
prints in file:

>   [Player information]
> Time: 12.16.35.18.07.21

**Comment by s88100** [comment]
if it is only needed for the server,
localtime and p->death_info.ctime are the same
Time: 14.59.46.18.07.21    (localtime)
Time: Sun Jul 18 14:59:46 2021    (p->death_info.ctime)
/src/server/display-ui.c :L1817
```
    if (server)
    {
        char buf_tm[MSG_LEN];
        time_t rawtime = time(NULL);
        struct tm *tm_info = localtime(&rawtime);

        strftime(buf_tm, MSG_LEN, "%H%M%S%d%m%y", tm_info);

        strnfmt(dumpname, sizeof(dumpname), "%s-%s-%s.txt", p->name, ht_show(&turn), buf_tm);
        if (dump_save(p, dumpname, true))
            plog("Character dump successful.");
        else
            plog("Character dump failed!");
    }
```
Man874365-136641-145946180721.txt

**Comment by s88100** [comment]
/src/server/display-ui.c :L1817  localtime(&p->death_info.time)
```
    if (server)
    {
        char buf_tm[MSG_LEN];
        struct tm *tm_info = localtime(&p->death_info.time);

        strftime(buf_tm, MSG_LEN, "%H%M%S%d%m%y", tm_info);

        strnfmt(dumpname, sizeof(dumpname), "%s-%s-%s.txt", p->name, ht_show(&turn), buf_tm);
        if (dump_save(p, dumpname, true))
            plog("Character dump successful.");
        else
            plog("Character dump failed!");
    }

```

**Comment by igroglaz** [comment]
https://github.com/igroglaz/Tangaria/pull/7
