### ISSUE TITLE
Cleanup after installing on Linux

### ISSUE THREAD

**Issue by Tokariew** [igroglaz/Tangaria#84]
Installer will currently leave `tangaria_setup_files` folder after installation of Tangaria is complete. Are these files needed for anything if not, should be removed… I think one of following 3 scenarios should be used instead of leaving folder after successful compilation:

- move completly `tangaria_setup_files` to /tmp -- no need to cleanup later
- remove `tangaria_setup_files` after compilation is done
- ask user what should be done with folder after compilation is done

**Comment by s88100** [comment]
for /tmp directory
```
SETUP_FILES="/tmp/tangaria_setup_files"

#TARGET_DIR=$(dirname "$(readlink -f "$0")")
#SETUP_FILES="${TARGET_DIR}/tangaria_setup_files"
```

_configure settings for offline installation_
CHECKLIST_UPDATE_DOWNLOAD_TANGARIA=OFF
CHECKLIST_UPDATE_DOWNLOAD_TANGARIA_RELEASE=OFF
